VikramWebRole/Controllers/queuecController.cs
using Microsoft.WindowsAzure.Storage.Queue;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VikramWebRole.Models;

namespace VikramWebRole.Controllers
{
    public class queuecController : Controller
    {
        ConnectionString ConnectionObj = new ConnectionString();
        // GET: queuec
        public ActionResult Index()
        {
            return View();
        }

        #region Queue Implementation
        public ActionResult CreateQueue()
        {
            return View();
        }
        [HttpPost]
        public ActionResult QueuePost(QueueModel qm)
        {
            CloudQueueMessage message = new CloudQueueMessage(qm.Message);
            ConnectionObj.Queue.AddMessage(message);
            qm.Message = string.Empty;


            CloudQueueMessage peekedMessage = ConnectionObj.Queue.PeekMessage();
            if (peekedMessage != null)
                ViewData["msg"] = peekedMessage.AsString;

            return RedirectToAction("CreateQueue");
        }
        public FileResult DownloadQueueFile()
        {
            ConnectionString Con = new ConnectionString();
            string appendblob = "https://vikramastoragedb.blob.core.windows.net/vikramcontainer/VikramQueue.txt";
            string contentType = MimeMapping.GetMimeMapping(appendblob);
            HttpWebRequest aRequest = (HttpWebRequest)WebRequest.Create(appendblob);
            HttpWebResponse aResponse = (HttpWebResponse)aRequest.GetResponse();
            return File(aResponse.GetResponseStream(), contentType, "VikramQueue.txt");
        }
        #endregion
    }
}

VikramWebRole/Views/queuec/CreateQueue.cshtml
@model VikramWebRole.Models.QueueModel
@{
    ViewBag.Title = "CreateQueue";
}

<h2>CreateQueue</h2>
@using (Html.BeginForm("QueuePost", "queuec", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Download", "DownloadQueueFile", null, new { @class = "btn btn-default" })
            </div>

        </div>
    </div>
}