VikramWebRole/Controllers/blobsascController.cs
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VikramWebRole.Models;

namespace VikramWebRole.Controllers
{
    public class blobsascController : Controller
    {
        ConnectionString ConnectionObj = new ConnectionString();
        // GET: blobsasc
        public ActionResult Index()
        {
            return View();
        }
        #region Shared Access Signature Implementation
        public ActionResult UploadBlobBySAS()
        {
            BlobModel mdl = null;
            List<BlobModel> lstmdl = new List<BlobModel>();
            foreach (IListBlobItem item in ConnectionObj.PContainer.ListBlobs(null, false))
            {
                mdl = new BlobModel();
                if (item.GetType() == typeof(CloudBlockBlob))
                {
                    CloudBlockBlob blob = (CloudBlockBlob)item;
                    ViewBag.BlobFile = blob.Uri;
                    mdl.DocUrl = blob.Uri.ToString();
                    mdl.FileName = blob.Name;
                    lstmdl.Add(mdl);
                    mdl.Urls = lstmdl;
                }
            }
            return View(lstmdl);
        }
        [HttpPost]
        public ActionResult UploadBlobSign()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    CloudBlockBlob blockBlob = ConnectionObj.PContainer.GetBlockBlobReference(fileName);

                    blockBlob.UploadFromStream(file.InputStream);
                }
            }
            return RedirectToAction("UploadBlobBySAS");
        }
        public ActionResult DownloadDocShared(string docfile, string docname)
        {
            string reslink = string.Empty;
            string tmpval = Convert.ToString(TempData["docfile"]);
            if (tmpval == docfile)
            {
                reslink = TempData["link"].ToString();
            }
            else
            {
                reslink = GetBlobSasUri(ConnectionObj.PContainer, docname);
                TempData["docfile"] = docfile;
                TempData["link"] = reslink;
            }
            string contentType = string.Empty;

            if (docname.Contains(".pdf"))
            {
                contentType = "application/pdf";
            }
            else if (docname.Contains(".docx"))
            {
                contentType = "application/docx";
            }
            else
            {
                contentType = MimeMapping.GetMimeMapping(docfile);
            }
            return Redirect(reslink);
        }
        static string GetBlobSasUri(CloudBlobContainer Pcontainer, string filename)
        {
            CloudBlockBlob blob = Pcontainer.GetBlockBlobReference(filename);
            SharedAccessBlobPolicy sasConstraints = new SharedAccessBlobPolicy();
            sasConstraints.SharedAccessStartTime = DateTime.UtcNow.AddMinutes(-5);
            sasConstraints.SharedAccessExpiryTime = DateTime.UtcNow.AddSeconds(30);
            sasConstraints.Permissions = SharedAccessBlobPermissions.Read;
            string sasBlobToken = blob.GetSharedAccessSignature(sasConstraints);
            return blob.Uri + sasBlobToken;
        }
        #endregion
    }
}

VikramWebRole/Views/blobsasc/UploadBlobBySAS.cshtml
@model List<VikramWebRole.Models.BlobModel>
@{
    ViewBag.Title = "UploadBlobBySAS";
}

<h2>UploadBlobBySAS</h2>
@using (Html.BeginForm("UploadBlobSign", "blobsasc", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td><b>Select File To Upload</b></td>
            <td>
                <input type="file" name="file" id="fileToUpload" />

            </td>

        </tr>
        <tr>
            <td><input type="submit" name="Submit" id="Submit" value="Upload" /></td>

        </tr>
    </table>
    <div class="upload">
        <div style="width: 500px;">
            <table id="uloadTable" border="1">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @if (Model.Count > 0)
                    {
                        foreach (var element in Model[0].Urls)
                        {
                            <tr id="@element.FileName">
                                <td>

                                    <img width="100" height="50" border="0" src="@element.DocUrl" class="viewc">
                                </td>
                                <td>

                                    @Html.ActionLink("Download", "DownloadDocShared", new { docfile = @element.DocUrl, docname = @element.FileName })

                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>

        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/jscript">
    $(document).ready(function ()
    {

        $("#Submit").click(function() {
            if ($('#fileToUpload').val() == "") {

                alert("Please upload file");
                return false;
            }
            else {
                return checkfile();
            }
        });
    });
    function checkfile() {
        var file = getNameFromPath($("#fileToUpload").val());
        if (file != null) {
            var extension = file.substr((file.lastIndexOf('.') + 1));
            // alert(extension);
            switch (extension) {
                case 'jpg':
                case 'png':
                case 'gif':
                case 'pdf':
                    flag = true;
                    break;
                default:
                    flag = false;
            }
        }
        if (flag == false) {
            $("#spanfile").text("You can upload only jpg,png,gif,pdf extension file");
            return false;
        }
    }
</script>