VikramWebRole/Controllers/blobcController.cs
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VikramWebRole.Models;

namespace VikramWebRole.Controllers
{
    public class blobcController : Controller
    {
        ConnectionString ConnectionObj = new ConnectionString();
        // GET: blobc
        public ActionResult Index()
        {
            return View();
        }
        #region Upload -Download Document
        public ActionResult UploadBlob()
        {
            BlobModel mdl = null;
            List<BlobModel> lstmdl = new List<BlobModel>();
                foreach (IListBlobItem item in ConnectionObj.Container.ListBlobs(null, false))
                {
                    mdl = new BlobModel();
                    if (item.GetType() == typeof(CloudBlockBlob))
                    {
                        CloudBlockBlob blob = (CloudBlockBlob)item;

                        ViewBag.BlobFile = blob.Uri;
                        mdl.DocUrl = blob.Uri.ToString();
                        mdl.FileName = blob.Name;
                        lstmdl.Add(mdl);
                        mdl.Urls = lstmdl;
                    }
                }
            return View(lstmdl);
        }

        [HttpPost]
        public ActionResult UploadDoc()
        {
            ConnectionObj.Container.SetPermissions(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    CloudBlockBlob blockBlob = ConnectionObj.Container.GetBlockBlobReference(fileName);
                    blockBlob.UploadFromStream(file.InputStream);
                }
            }

            return RedirectToAction("UploadBlob");
        }
        public FileResult DownloadBlob(string docfile, string docname)
        {
            string contentType = string.Empty;
            if (docname.Contains(".pdf"))
            {
                contentType = "application/pdf";
            }

            else if (docname.Contains(".docx"))
            {
                contentType = "application/docx";
            }
            else
            {
                contentType = MimeMapping.GetMimeMapping(docfile); ;

            }
            HttpWebRequest aRequest = (HttpWebRequest)WebRequest.Create(docfile);
            HttpWebResponse aResponse = (HttpWebResponse)aRequest.GetResponse();
            return File(aResponse.GetResponseStream(), contentType, docname);
        }
        #endregion
    }
}

VikramWebRole/Views/blobc/UploadBlob.cshtml
@model List<VikramWebRole.Models.BlobModel>
@{
    ViewBag.Title = "UploadBlob";
}

<h2>UploadBlob</h2>
@using (Html.BeginForm("UploadDoc", "blobc", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td><b>Select File To Upload</b></td>
            <td>
                <input type="file" name="file" id="fileToUpload" />

            </td>

        </tr>
        <tr>
            <td><input type="submit" name="Submit" id="Submit" value="Upload" /></td>
        </tr>
    </table>
    <div class="upload">
        <div style="width: 500px;">
            <table id="uloadTable" border="1">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                   @{ 
                       try
                       {
                        foreach (var element in Model[0].Urls)
                        {
                            <tr id="@element.FileName">
                                <td>

                                    <img width="100" height="50" border="0" src="@element.DocUrl" class="viewc">
                                </td>
                                <td>
                                    @Html.ActionLink("Download", "DownloadBlob", new { docfile = @element.DocUrl, docname = @element.FileName })
                                </td>
                            </tr>
                        }
                       }
                 catch
                           { }
                        }
                </tbody>
            </table>

        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/jscript">
    $(document).ready(function ()
    {

        $("#Submit").click(function() {
            if ($('#fileToUpload').val() == "") {

                alert("Please upload file");
                return false;
            }
            else {
                return checkfile();
            }
        });
    });
    function checkfile() {
        var file = getNameFromPath($("#fileToUpload").val());
        if (file != null) {
            var extension = file.substr((file.lastIndexOf('.') + 1));
            // alert(extension);
            switch (extension) {
                case 'jpg':
                case 'png':
                case 'gif':
                case 'pdf':
                    flag = true;
                    break;
                default:
                    flag = false;
            }
        }
        if (flag == false) {
            $("#spanfile").text("You can upload only jpg,png,gif,pdf extension file");
            return false;
        }
    }
</script>