VikramWebRole/Controllers/tablecController.cs
using Microsoft.WindowsAzure.Storage.Table;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VikramWebRole.Models;

namespace VikramWebRole.Controllers
{
    public class tablecController : Controller
    {
        ConnectionString ConnectionObj = new ConnectionString();
        // GET: tablec
        public ActionResult Index()
        {
            return View();
        }

        #region Table Storage Implementation
        public ActionResult CreateTable(string pkey = "", string rkey = "")
        {
            TableOperation retrieveOperation = TableOperation.Retrieve<TableModel>(pkey, rkey);

            TableResult retrievedResult = ConnectionObj.Table.Execute(retrieveOperation);
            TableModel objProp = new TableModel();
            if (retrievedResult.Result != null)
            {

                objProp.ContactNo = pkey;
                objProp.Email = rkey;
                objProp.ContactNo = ((TableModel)retrievedResult.Result).ContactNo;
                objProp.FName = ((TableModel)retrievedResult.Result).FName;
                objProp.LName = ((TableModel)retrievedResult.Result).LName;
                objProp.Address = ((TableModel)retrievedResult.Result).Address;
            }
            return View(objProp);
        }
        [HttpPost]
        public ActionResult InsertTable(TableModel TabControl)
        {
            TableOperation retrieveOperation = TableOperation.Retrieve<TableModel>(TabControl.ContactNo, TabControl.Email);
            TableResult retrievedResult = ConnectionObj.Table.Execute(retrieveOperation);
            TableModel updateEntity = (TableModel)retrievedResult.Result;
            if (updateEntity == null)
            {
                ConnectionObj.Table.CreateIfNotExists();

                TableModel objTab = new TableModel(TabControl.ContactNo, TabControl.Email);
                objTab.FName = TabControl.FName;
                objTab.LName = TabControl.LName;
                objTab.Address = TabControl.Address;
                objTab.ContactNo = TabControl.ContactNo;
                TableOperation insertOperation = TableOperation.Insert(objTab);
                ConnectionObj.Table.Execute(insertOperation);
            }
            else
            {
                updateEntity.FName = TabControl.FName;
                updateEntity.LName = TabControl.LName;
                updateEntity.Address = TabControl.Address;
                updateEntity.ContactNo = TabControl.ContactNo;
                TableOperation updateOperation = TableOperation.Replace(updateEntity);
                ConnectionObj.Table.Execute(updateOperation);
            }

            return RedirectToAction("TableStorage");
        }
        public ActionResult TableStorage()
        {
            TableQuery<TableModel> query = new TableQuery<TableModel>();
            List<TableModel> tableList = new List<TableModel>();
            if (ConnectionObj.Table.Exists())
            {
                foreach (TableModel entity in ConnectionObj.Table.ExecuteQuery(query))
                {
                    TableModel obj = new TableModel();
                    obj.ContactNo = entity.PartitionKey;
                    obj.Email = entity.RowKey;
                    obj.FName = entity.FName;
                    obj.LName = entity.LName;
                    obj.Address = entity.Address;
                    obj.ContactNo = entity.ContactNo;
                    tableList.Add(obj);
                }
            }
            return View(tableList);
        }
        public ActionResult DeleteTable(string pkey = "", string rkey = "")
        {
            TableOperation retrieveOperation = TableOperation.Retrieve<TableModel>(pkey, rkey);
            TableResult retrievedResult = ConnectionObj.Table.Execute(retrieveOperation);
            TableModel deleteEntity = (TableModel)retrievedResult.Result;
            if (deleteEntity != null)
            {
                TableOperation deleteOperation = TableOperation.Delete(deleteEntity);
                ConnectionObj.Table.Execute(deleteOperation);
            }
            return RedirectToAction("TableStorage");
        }
        #endregion
    }
}

VikramWebRole/Views/tablec/CreateTable.cshtml
@model VikramWebRole.Models.TableModel
@{
    ViewBag.Title = "CreateTable";
}

<h2>CreateTable</h2>
@using (Html.BeginForm("InsertTable", "tablec", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "TableStorage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VikramWebRole/Views/tablec/TableStorage.cshtml
@model IEnumerable<VikramWebRole.Models.TableModel>
@{
    ViewBag.Title = "TableStorage";
}

<h2>TableStorage</h2>
@Html.ActionLink("Create", "CreateTable")
<table class="table">
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>
        <th>
            Contact No
        </th>
        <th>
            Address
        </th>
        <th>
            Add
        </th>
        <th>
            Edit
        </th>
        <th>
            Delete
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Create", "CreateTable")
            </td>
            <td>
                @Html.ActionLink("Edit", "CreateTable", new { pkey = item.ContactNo, rkey = item.Email })
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteTable", new { pkey = item.ContactNo, rkey = item.Email })
            </td>
        </tr>
    }
</table>